# Generated by Django 4.0.1 on 2022-01-24 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6)),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('city', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=200)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='souvenirs_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='PostCard',
            fields=[
                ('postcrossing_id', models.AutoField(primary_key=True, serialize=False)),
                ('send_date', models.DateField(auto_now_add=True)),
                ('receive_date', models.DateField(auto_now=True)),
                ('send_user_img', models.ImageField(upload_to='media/')),
                ('receive_user_img', models.ImageField(upload_to='media/')),
                ('status', models.CharField(choices=[('TR', 'Travelling'), ('RCV', 'Received')], default='Travelling', max_length=10)),
                ('receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcard_receive_user', to=settings.AUTH_USER_MODEL)),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcard_send_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
