# Generated by Django 4.0.2 on 2022-02-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=3, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='souvenir',
            name='slug',
            field=models.SlugField(max_length=30, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(max_length=30, null=True, verbose_name='URL'),
        ),
    ]
