# Generated by Django 4.0.1 on 2022-01-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='postcard',
            options={'verbose_name': 'Postcard', 'verbose_name_plural': 'Postcards'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'User_information', 'verbose_name_plural': 'User_informations'},
        ),
        migrations.AlterField(
            model_name='postcard',
            name='receive_user_img',
            field=models.ImageField(null=True, upload_to='receive/'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='send_user_img',
            field=models.ImageField(null=True, upload_to='send/'),
        ),
    ]
