# Generated by Django 4.0.1 on 2022-01-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs_app', '0002_alter_country_options_alter_postcard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='receive_user_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='receive/'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='send_user_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='send/'),
        ),
    ]
