# Generated by Django 4.0.2 on 2022-02-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs_app', '0003_remove_souvenir_extra_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='souvenir',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
