# Generated by Django 4.0.2 on 2022-02-04 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('souvenirs_app', '0003_alter_postcard_receive_user_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('souvenir_id', models.AutoField(primary_key=True, serialize=False)),
                ('send_date', models.DateField(auto_now_add=True)),
                ('receive_date', models.DateField(auto_now=True)),
                ('send_user_img', models.ImageField(blank=True, default='no-photo.png', null=True, upload_to='send/')),
                ('receive_user_img', models.ImageField(blank=True, default='no-photo.png', null=True, upload_to='receive/')),
                ('status', models.CharField(choices=[('TR', 'Travelling'), ('RCV', 'Received')], default='Travelling', max_length=10)),
                ('receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_user', to=settings.AUTH_USER_MODEL)),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Souvenir',
                'verbose_name_plural': 'Souvenirs',
            },
        ),
        migrations.DeleteModel(
            name='PostCard',
        ),
    ]
