# Generated by Django 4.0.2 on 2022-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs_app', '0005_alter_souvenir_receive_user_alter_souvenir_send_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=3, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='souvenir',
            name='slug',
            field=models.SlugField(max_length=30, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(max_length=30, verbose_name='URL'),
        ),
    ]
