# Generated by Django 4.0.2 on 2022-02-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs_app', '0006_alter_country_slug_alter_souvenir_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenir',
            name='receive_user',
            field=models.ForeignKey(on_delete=models.SET('deleted user'), related_name='receive_user', to='souvenirs_app.userinfo'),
        ),
        migrations.AlterField(
            model_name='souvenir',
            name='send_user',
            field=models.ForeignKey(on_delete=models.SET('deleted user'), related_name='send_user', to='souvenirs_app.userinfo'),
        ),
    ]
