# Generated by Django 4.0.2 on 2022-02-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs_app', '0004_souvenir_delete_postcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='souvenir',
            name='extra_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
