# Generated by Django 4.0.2 on 2022-02-14 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('souvenirs_app', '0007_alter_souvenir_receive_user_alter_souvenir_send_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenir',
            name='receive_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receive_user', to='souvenirs_app.userinfo'),
        ),
        migrations.AlterField(
            model_name='souvenir',
            name='send_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_user', to='souvenirs_app.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
