# Generated by Django 4.0.2 on 2022-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs_app', '0008_alter_souvenir_receive_user_alter_souvenir_send_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenir',
            name='status',
            field=models.CharField(choices=[('TR', 'Travelling'), ('RCV', 'Received')], max_length=10),
        ),
    ]
