# Generated by Django 4.0.2 on 2022-02-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs_app', '0008_userinfo_avatar_userinfo_date_of_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userinfo', to='souvenirs_app.country'),
        ),
    ]
