# Generated by Django 4.0.2 on 2022-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs_app', '0010_alter_country_code_alter_country_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
