# Generated by Django 4.0.2 on 2022-02-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs_app', '0011_rename_message_souvenir_send_user_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenir',
            name='receive_date',
            field=models.DateField(),
        ),
    ]
